import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  'documentation': [{type: 'autogenerated', dirName: 'documentation'}],
  'meeting-minutes': [{type: 'autogenerated', dirName: 'meeting-minutes'}],
};

export default sidebars;
